function options = MS_S2D_ExtractOptions(p, fracBlack, fracBlack2)
    options.outBW      = p.Results.outBW;
    options.outSeg     = p.Results.outSeg; % name for the output Seg file
    options.outRGB     = p.Results.outRGB; % name for the output RGB file
    options.outThr     = p.Results.outThr;
    options.membPr     = p.Results.membPr;
    options.mitoPr     = p.Results.mitoPr;
    options.mitoMembPr = p.Results.mitoMembPr;
    options.subWin     = p.Results.subWin;
    options.compiled_code = 0;
    if isnumeric(fracBlack)     % original Matlab code
        options.fracBlack = fracBlack;
        options.fracBlack2= fracBlack2;
        options.verbose   = p.Results.verbose;
        options.heatmap   = p.Results.heatmap;
        options.debug     = p.Results.debug;     
        options.hist      = p.Results.hist;
        options.showIter  = p.Results.showIter;
        options.dispOn    = p.Results.dispOn;
        options.dispOn2   = p.Results.dispOn2;
        options.closeAll  = p.Results.closeAll;
        options.darkStr   = p.Results.darkStr;
        options.useMembPr = p.Results.useMembPr;
        options.vesicles  = p.Results.vesicles;
        options.padding   = p.Results.padding;
        options.RGB       = p.Results.RGB;       % display the RGB labels
        options.numRef    = p.Results.numRef;
        options.incRef    = p.Results.incRef;    % perform the incrementation refinement only
        options.nx        = p.Results.nx;
        options.ny        = p.Results.ny;
        options.dx        = p.Results.dx;
        options.dy        = p.Results.dy;
        options.sx        = p.Results.sx;
        options.sy        = p.Results.sy;
        options.maxSize   = p.Results.maxSize;
        options.minSize   = p.Results.minSize;
        options.maxWin    = p.Results.maxWin;
        options.minWin    = p.Results.minWin;
        options.minMitoFr = p.Results.minMitoFr;
        options.maxMitoFr = p.Results.maxMitoFr;
        options.resize    = p.Results.resize;
        options.thr       = p.Results.thr;
        options.thr2      = p.Results.thr2;
        options.thrMembPr = p.Results.thrMembPr;
        options.q         = p.Results.q;
        options.a         = p.Results.a;
    else
        options.compiled_code = 1;    % compiled code
        options.fracBlack     =       str2double(fracBlack);
        options.fracBlack2    =       str2double(fracBlack2);
        options.verbose       = int32(str2double(p.Results.verbose));
        options.heatmap       = int32(str2double(p.Results.heatmap));
        options.debug         = int32(str2double(p.Results.debug));
        options.hist          = int32(str2double(p.Results.hist));
        options.showIter      = int32(str2double(p.Results.showIter));
        options.dispOn        = int32(str2double(p.Results.dispOn));
        options.dispOn2       = int32(str2double(p.Results.dispOn2));
        options.closeAll      = int32(str2double(p.Results.closeAll));
        options.darkStr       = int32(str2double(p.Results.darkStr));
        options.padding       = int32(str2double(p.Results.padding));
        options.RGB           = int32(str2double(p.Results.RGB));
        options.numRef        = int32(str2double(p.Results.numRef));
        options.incRef        = int32(str2double(p.Results.incRef));
        options.useMembPr     = int32(str2double(p.Results.useMembPr));
        options.vesicles      = int32(str2double(p.Results.vesicles));
        options.nx            = int32(str2double(p.Results.nx));
        options.ny            = int32(str2double(p.Results.ny));
        options.dx            = int32(str2double(p.Results.dx));
        options.dy            = int32(str2double(p.Results.dy));
        options.sx            = int32(str2double(p.Results.sx));
        options.sy            = int32(str2double(p.Results.sy));
        options.maxSize       = int32(str2double(p.Results.maxSize));
        options.minSize       = int32(str2double(p.Results.minSize));
        options.maxWin        = int32(str2double(p.Results.maxWin));
        options.minWin        = int32(str2double(p.Results.minWin));
        options.minMitoFr     = int32(str2double(p.Results.minMitoFr));
        options.maxMitoFr     = int32(str2double(p.Results.maxMitoFr));
        options.resize        = int32(str2double(p.Results.resize)); 
        options.thr           =       str2double(p.Results.thr);
        options.thr2          =       str2double(p.Results.thr2);
        options.thrMembPr     =       str2double(p.Results.thrMembPr);
        options.q             =       str2double(p.Results.q);
        options.a             =       str2double(p.Results.a);
    end
    return

